### ISSUE TITLE
Slight mistake in #677bd4c

### ISSUE THREAD

**Issue by Egoscio-zz** [joshgordon/table-flip#1]
`console.warn` proxy applies `console.error` method instead of its respective functions. Mistake seems to be from commit [#677bd4c](https://github.com/joshgordon/table-flip/commit/677bd4c5afd3c3f408170e3c97dc4e343c2fbcb0), and renders `w` a declared but unused variable.

**Comment by joshgordon** [comment]
Nice find, thanks for the report!
